#!/bin/bash
#SBATCH -J post           # Job name
#SBATCH -o post.out       # Name of stdout output file
#SBATCH -e post.err       # Name of stderr error file
#SBATCH -p development        # Queue (partition) name
#SBATCH -N 1                # Total # of nodes
#SBATCH -n 1              # Total # of mpi tasks
#SBATCH -t 01:30:00          # Run time (hh:mm:ss)
#SBATCH --mail-type=all      # Send email at begin and end of job
#SBATCH --mail-user=namo26june@gmail.com
#SBATCH -A DMS21031

#rename 'fort.64' 'fort.64.old' PE*/*
rm PE*/DG.63
rm PE*/DG.65
./adcpost < out.prep
